replicaCount: 1

image:
  repository: ghcr.io/seanchuatech/order-processing-system/inventory-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8093

env:
  PORT: "8093"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/728399088474/ops-sandbox-payment-processed-inventory"

serviceAccount:
  create: true
  name: "inventory-service"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::728399088474:role/ops-sandbox-inventory-service-role"

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

externalSecret:
  enabled: true
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  keys:
    - DATABASE_URL
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /ops-sandbox/inventory-service/DATABASE_URL
