apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: inventory-service
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm-charts/app-generic
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: inventory-service-values
      valuesKey: inventory-service-values.yaml
