apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - order-service.yaml
  - notification-service.yaml

configMapGenerator:
  - name: order-service-values
    files:
      - order-service-values.yaml
  - name: notification-service-values
    files:
      - notification-service-values.yaml
