replicaCount: 1
image:
  repository: ghcr.io/seanchuatech/order-processing-system/notification-service
  tag: b49539e
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8081
env:
  PORT: "8081"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "orders.created"
  KAFKA_GROUP_ID: "notification-group"
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
externalSecret:
  enabled: false
