// ElasticMQ configuration file
// See: https://github.com/softwaremill/elasticmq

include classpath("application.conf")

// What is the node address of the SQS emulator
node-address {
    protocol = "http"
    host = "localhost"
    port = 9324
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
    // Limit performance lag for testing
    sqs-limits = "strict"
}

// Queue definitions
queues {
    orders-created {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "orders-created-dlq"
            maxReceiveCount = 3
        }
    }
    orders-created-dlq {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
    }
}
