// ElasticMQ configuration file
// See: https://github.com/softwaremill/elasticmq

include classpath("application.conf")

// What is the node address of the SQS emulator
node-address {
    protocol = "http"
    host = "localhost"
    port = 9324
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
    // Limit performance lag for testing
    sqs-limits = "strict"
}

// Queue definitions
queues {
    order-pending {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "order-pending-dlq"
            maxReceiveCount = 3
        }
    }
    order-pending-dlq {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
    }

    payment-processed-notification {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "payment-processed-notification-dlq"
            maxReceiveCount = 3
        }
    }
    payment-processed-notification-dlq {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
    }

    payment-processed-inventory {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "payment-processed-inventory-dlq"
            maxReceiveCount = 3
        }
    }
    payment-processed-inventory-dlq {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
    }

    payment-processed-analytics {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "payment-processed-analytics-dlq"
            maxReceiveCount = 3
        }
    }
    payment-processed-analytics-dlq {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
    }
}
