apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - cluster-secret-store.yaml
  - external-services.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: order-service
    patch: |-
      - op: add
        path: /spec/source/helm/values
        value: |
          externalSecret:
            data:
              - secretKey: DATABASE_URL
                remoteRef:
                  key: order-service-secrets
                  property: DATABASE_URL
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: outbox-relay
    patch: |-
      - op: add
        path: /spec/source/helm/values
        value: |
          externalSecret:
            data:
              - secretKey: DATABASE_URL
                remoteRef:
                  key: order-service-secrets
                  property: DATABASE_URL
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: inventory-service
    patch: |-
      - op: add
        path: /spec/source/helm/values
        value: |
          externalSecret:
            data:
              - secretKey: DATABASE_URL
                remoteRef:
                  key: inventory-service-secrets
                  property: DATABASE_URL
