replicaCount: 1
image:
  repository: ghcr.io/seanchuatech/order-processing-system/payment-service
  tag: d9023a2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8092
env:
  PORT: "8092"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/728399088474/ops-sandbox-order-pending"
  SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:728399088474:ops-sandbox-payment-processed-topic"
serviceAccount:
  create: true
  name: "payment-service"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::728399088474:role/ops-sandbox-payment-service-role"
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
externalSecret:
  enabled: false
